# fly.toml app configuration file generated for practice-devcontainer on 2024-03-27T13:11:14Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'practice-devcontainer'
primary_region = 'nrt'
console_command = '/rails/bin/rails console'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
