default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: <%= ENV["MYSQL_ROOT_PASSWORD"] %>
  host: <%= ENV["DB_HOST"] %>

development:
  <<: *default
  database: <%= ENV["DEV_DB_NAME"] %>

test:
  <<: *default
  database: <%= ENV["TEST_DB_NAME"] %>

production:
  <<: *default
  database: <%= ENV["PROD_DB_NAME"] %>